### ISSUE TITLE
Panic from `print_text`

### ISSUE THREAD

**Issue by samtay** [Canop/termimad#23]
I've discovered a different panic from `print_text`, this one originating from splitting within a unicode char, i.e. not at a char boundary.

This is a reproducible example
```rust
use std::io::Write;
use termimad::*;

static MD: &str = "ZA\u{360}\u{321}\u{34a}\u{35d}LGΌ IS\u{36e}\u{302}\u{489}\u{32f}\u{348}\u{355}\u{339}\u{318}\u{331} T</b>O\u{345}\u{347}\u{339}\u{33a}Ɲ\u{334}ȳ\u{333} TH\u{318}<b>E\u{344}\u{309}\u{356} \u{360}P\u{32f}\u{34d}\u{32d}O\u{31a}\u{200b}N\u{310}Y\u{321} H\u{368}\u{34a}\u{33d}\u{305}\u{33e}\u{30e}\u{321}\u{338}\u{32a}\u{32f}E\u{33e}\u{35b}\u{36a}\u{344}\u{300}\u{301}\u{327}\u{358}\u{32c}\u{329} \u{367}\u{33e}\u{36c}\u{327}\u{336}\u{328}\u{331}\u{339}\u{32d}\u{32f}C\u{36d}\u{30f}\u{365}\u{36e}\u{35f}\u{337}\u{319}\u{332}\u{31d}\u{356}O\u{36e}\u{34f}\u{32e}\u{32a}\u{31d}\u{34d}";

fn main() {
    let skin = MadSkin::default();
    skin.print_text(MD);
}
```
resulting in the error
```
thread 'main' panicked at 'byte index 137 is not a char boundary; it is inside '\u{329}' (bytes 136..138) of `ZA͠͝LGΌ IS̱ͮ T</b>O̺ͅƝ̴ȳ̳ TH̘<b>Ë͖́ ͠P̯̭O̚N̐Y̡ H̯ͨE̩̾ ̯ͧC͖ͭO̪ͮ`', /Users/sam/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore/str/mod.rs:2052:47
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /Users/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1069
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1504
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:511
  11: rust_begin_unwind
             at src/libstd/panicking.rs:419
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:111
  13: core::str::slice_error_fail
             at src/libcore/str/mod.rs:0
  14: core::str::traits::<impl core::slice::SliceIndex<str> for core::ops::range::RangeFrom<usize>>::index::{{closure}}
             at /Users/sam/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore/str/mod.rs:2052
  15: core::option::Option<T>::unwrap_or_else
             at /Users/sam/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore/option.rs:428
  16: core::str::traits::<impl core::slice::SliceIndex<str> for core::ops::range::RangeFrom<usize>>::index
             at /Users/sam/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore/str/mod.rs:2052
  17: core::str::traits::<impl core::ops::index::Index<I> for str>::index
             at /Users/sam/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src/libcore/str/mod.rs:1780
  18: minimad::compound::Compound::cut_tail
             at /Users/sam/.cargo/registry/src/github.com-1ecc6299db9ec823/minimad-0.6.5/src/compound.rs:119
  19: termimad::wrap::hard_wrap_composite
             at src/wrap.rs:144
  20: termimad::wrap::hard_wrap_lines
             at src/wrap.rs:173
  21: termimad::text::FmtText::from_text
             at src/text.rs:44
  22: termimad::text::FmtText::from
             at src/text.rs:32
  23: termimad::skin::MadSkin::term_text
             at src/skin.rs:208
  24: termimad::skin::MadSkin::print_text
             at src/skin.rs:243
  25: text::main
             at examples/text/main.rs:8
  26: std::rt::lang_start::{{closure}}
             at /Users/sam/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/rt.rs:67
  27: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  28: std::panicking::try::do_call
             at src/libstd/panicking.rs:331
  29: std::panicking::try
             at src/libstd/panicking.rs:274
  30: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  31: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  32: std::rt::lang_start
             at /Users/sam/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/src/rust/src/libstd/rt.rs:67
  33: main
```
however you need to make sure your terminal width isn't too narrow / too wide. If you can't reproduce let me know and I will figure out the specific width necessary to repro.

**Comment by Canop** [comment]
I'll end up doing the width computation the hard and slow but correct way, as I do in broot...

@samtay I may be slow to fix this one as I'm going into holiday.

**Comment by Canop** [comment]
(I'm still on it... it will be one in less than one year!)



(probably)
